### ISSUE TITLE
gedit 3.28.1 plugin does not load 

### ISSUE THREAD

**Issue by kevinkayaks** [jefferyto/gedit-control-your-tabs#10]
on Ubuntu 18.04 with gedit 3.28.1 I install as directed in the readme, I open gedit and navigate to preferences/plugins. I see the new plugin control your tabs, and when I activate it I get an error; the plugin doesn't work. 

The error trace back in the shell is 
```

(gedit:5878): libpeas-WARNING **: 21:52:38.708: Error initializing Python Plugin Loader: PyGObject initialization failed
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'",))

(gedit:5878): libpeas-WARNING **: 21:52:38.708: Please check the installation of all the Python related packages required by libpeas and try again

(gedit:5878): libpeas-WARNING **: 21:52:38.708: Loader 'python3' is not a valid PeasPluginLoader instance

```

Any input is appreciated. I'd love to get the add on working. I assume this is a compatibility issue with gedit 3.28.1.

**Comment by jefferyto** [comment]
Are these packages installed on your system:

* libpeas-1.0-0
* libgirepository-1.0-1
* libpython3.6
* python3-gi
* python3-gi-cairo

Also, are you using virtualenv?

**Comment by kevinkayaks** [comment]
Hi Jeffery, 

I have all of those packages. You mean virtualenv in python? I have a conda installation in which I use virtual environments. Please clarify and I'll check anything you need to know 

thanks,
Kevin

**Comment by jefferyto** [comment]
From the error messages (`"No module named 'gi'"`) it appears python3 cannot find the gi module. I'm not familiar with conda, but I would suggest making sure your `python`/`python3` executables are the system default ones, then try to enabling the plugin again.

You can also try running `python3 -c "import gi"` on the command line (suggested from [here](https://github.com/coala/coala-gedit/issues/16#issuecomment-215670464)). There should be no errors.

Do you have any other python plugins installed and enabled? You can also try disabling all plugins before enabling this one, there may be a conflict of some kind.

I'm pretty sure the plugin works on your OS and gedit versions because I'm using the exact same versions, and I also tried the plugin in a Ubuntu 18.04.1 live iso vm and it worked there too.

**Comment by kevinkayaks** [comment]
That's the issue jeffery! 

```
[kevin@herbert:~] $ python3 -c "import gi" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'

```

**Comment by jefferyto** [comment]
This [comment](https://bugs.launchpad.net/linuxmint/+bug/1307010/comments/1) also suggests a `PYTHONPATH` environment variable may also interfere with python finding the right libraries.

**Comment by jefferyto** [comment]
If I run `which python3` on the command line, I get `/usr/bin/python3`, which is a symlink to `/usr/bin/python3.6`. I suspect you may see different results on your system.

**Comment by jefferyto** [comment]
I think this [launchpad question/answer](https://answers.launchpad.net/ubuntu/+source/gedit-plugins/+question/672490) may address your issue exactly :-D

**Comment by kevinkayaks** [comment]
Fixed! The problem was a conflict between python distributions. The gi package was located at `/usr/lib/python3/dist-packages/gi`. The python version required by gedit add-ons is `/usr/bin/python3.6`, and the python version symlinked to `python3` was `home/kevin/anaconda3/bin/python3.6`, so gedit couldn't find it. 

In order to fix it I added a path to the proper packages within the `python3` distribution's bin folder: 

`echo /usr/lib/python3/dist-packages > /home/kevin/anaconda3/lib/python3.6/site-packages/dist-package.pth`

Now it works great. Thanks again Jeffery for the careful help and your gedit add-on.
