### ISSUE TITLE
Switch between tab groups

### ISSUE THREAD

**Issue by sojusnik** [jefferyto/gedit-control-your-tabs#11]
Instead of tabs, I recently started using tab groups (`ctrl+alt+n`). Since you can break your fingers with the default shortcuts `shift+ctrl+alt+pageup/pagedown` (I have to additionally hold `fn` on my notebook to activate `pageup/pagedown`) for switching tab groups, I want to modify your plugin to switch tab groups with `ctrl+tab`. I'm not a programmer, but could figure things out if you could tell me what to replace in your code in order to achieve that behavior.

Thanks in advance!

**Comment by jefferyto** [comment]
Thanks for asking - I think this is the first time I've heard of someone using tab groups :laughing: 

Instead of hacking up this plugin, I wrote another one to do this: [Tab Group Salute](https://github.com/jefferyto/gedit-tab-group-salute).

It uses <kbd>Ctrl</kbd>+<kbd>\`</kbd> (backquote / backtick) though; I thought that combination would make more sense. It shouldn't be too hard to change the shortcut keys inside the code if you want, though it won't be possible to bind to <kbd>Ctrl</kbd>+<kbd>Tab</kbd> directly (it's one of the shortcuts reserved by GNOME).

**Comment by sojusnik** [comment]
Many thanks! Your solution with `'` makes more sense too! The new plugin works well, but I can't cycle back with `shift`. Do you observe this too?

**Comment by jefferyto** [comment]
You mean <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>\`</kbd> isn't working for you?

**Comment by sojusnik** [comment]
> You mean Ctrl+Shift+` isn't working for you?

Yes, but only when using a German layout. See my addition above.

**Comment by jefferyto** [comment]
Technically the shortcut key is <kbd>Ctrl</kbd>+<kbd>~</kbd>; in the US layout backtick and tilde are on the same key but I believe tilde is on a different key in German layouts. I'll have to think about how to detect the current keyboard and adjust the shortcuts dynamically.

**Comment by jefferyto** [comment]
Just pushed a new version, it should work regardless of keyboard layout.

**Comment by sojusnik** [comment]
Works great now, thanks!

**Comment by jefferyto** [comment]
:+1:
